#
# 服务器 配置
#
server:
  # 端口
  port: 9000
#
# 日志 配置
#
logging:
  # 日志等级
  level:
    # web 日志,当且仅当开发时才可使用 web 为 debug
    web: debug
#
# Spring 配置
#
spring:
  #
  # thymeleaf 配置
  thymeleaf:
    # 是否启用缓存
    cache: false
